export const groupAStandings = [
  {
    team: "Santos FC",
    played: 2,
    won: 2,
    draw: 0,
    lost: 0,
    goalsFor: 5,
    goalsAgainst: 2,
    points: 6,
  },
  {
    team: "Blue Sharks",
    played: 2,
    won: 1,
    draw: 0,
    lost: 1,
    goalsFor: 3,
    goalsAgainst: 3,
    points: 3,
  },
  {
    team: "Golden Boys",
    played: 2,
    won: 0,
    draw: 1,
    lost: 1,
    goalsFor: 1,
    goalsAgainst: 4,
    points: 1,
  },
  {
    team: "Real Amigos",
    played: 2,
    won: 0,
    draw: 1,
    lost: 1,
    goalsFor: 2,
    goalsAgainst: 5,
    points: 1,
  },
];

export const groupBStandings = [
  {
    team: "FC Milano",
    played: 2,
    won: 2,
    draw: 0,
    lost: 0,
    goalsFor: 6,
    goalsAgainst: 1,
    points: 6,
  },
  {
    team: "Night Owls",
    played: 2,
    won: 1,
    draw: 0,
    lost: 1,
    goalsFor: 4,
    goalsAgainst: 3,
    points: 3,
  },
  {
    team: "Street Legends",
    played: 2,
    won: 1,
    draw: 0,
    lost: 1,
    goalsFor: 2,
    goalsAgainst: 3,
    points: 3,
  },
  {
    team: "Black Eagles",
    played: 2,
    won: 0,
    draw: 0,
    lost: 2,
    goalsFor: 1,
    goalsAgainst: 6,
    points: 0,
  },
];